# Generated by Django 5.2.1 on 2025-06-29 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_es_conductor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario del sistema', 'verbose_name_plural': 'Usuarios del sistema'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='camion_asignado',
            field=models.CharField(blank=True, max_length=50, verbose_name='Camión asignado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.TextField(default='Sin dirección registrada', verbose_name='Dirección completa'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pregunta_seguridad_1',
            field=models.CharField(default='¿Cuál es el nombre de tu primera mascota?', max_length=200, verbose_name='Pregunta de seguridad 1'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pregunta_seguridad_2',
            field=models.CharField(default='¿En qué ciudad naciste?', max_length=200, verbose_name='Pregunta de seguridad 2'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='respuesta_seguridad_1',
            field=models.CharField(default='Respuesta temporal', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Respuesta 1'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='respuesta_seguridad_2',
            field=models.CharField(default='Respuesta temporal', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Respuesta 2'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default='0000000000', max_length=20, verbose_name='Teléfono de contacto'),
        ),
    ]
