# Generated by Django 5.2.1 on 2025-07-05 04:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_fix_preguntas_seguridad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='pregunta_seguridad_1',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='pregunta_seguridad_2',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='respuesta_seguridad_1',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='respuesta_seguridad_2',
        ),
        migrations.AddField(
            model_name='usuario',
            name='pregunta_1',
            field=models.CharField(choices=[('ciudad', '¿En qué ciudad naciste?'), ('comida', '¿Cuál es tu comida favorita?')], default='ciudad', max_length=20, verbose_name='Pregunta de seguridad 1'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pregunta_2',
            field=models.CharField(choices=[('ciudad', '¿En qué ciudad naciste?'), ('comida', '¿Cuál es tu comida favorita?')], default='comida', max_length=20, verbose_name='Pregunta de seguridad 2'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='respuesta_1',
            field=models.CharField(default='respuesta_default_1', max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Respuesta 1'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='respuesta_2',
            field=models.CharField(default='respuesta_default_2', max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Respuesta 2'),
        ),
    ]
