# Generated by Django 5.2.1 on 2025-07-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_add_preguntas_seguridad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='pregunta_1',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='pregunta_2',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='respuesta_1',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='respuesta_2',
        ),
        migrations.AddField(
            model_name='usuario',
            name='token_recuperacion',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
    ]
