# Generated by Django 5.2.1 on 2025-07-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_add_token_recuperacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='token_recuperacion',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
