# Generated by Django 5.2.1 on 2025-06-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despacho',
            name='debe_total',
        ),
        migrations.AddField(
            model_name='cliente',
            name='debe_total',
            field=models.IntegerField(default=0),
        ),
    ]
