# Generated by Django 5.2.1 on 2025-06-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_despacho_debe_total_cliente_debe_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='despacho',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
