# Generated by Django 5.2.1 on 2025-07-22 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_despacho_entregado_despacho_notas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='precio_botellon',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=5),
        ),
        migrations.AddField(
            model_name='cliente',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='despacho',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=5),
        ),
        migrations.AddField(
            model_name='despacho',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='clientes.cliente')),
            ],
        ),
    ]
