# Generated by Django 5.2.1 on 2025-07-27 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_precio_botellon_cliente_saldo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRastreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia_actualizacion', models.IntegerField(default=60, help_text='Frecuencia de actualización en segundos')),
                ('rastreo_activo', models.BooleanField(default=True, help_text='Indica si el rastreo está activo')),
                ('radio_alertas', models.DecimalField(decimal_places=2, default=5.0, help_text='Radio en km para alertas de zona', max_digits=5)),
                ('notificaciones_email', models.BooleanField(default=True, help_text='Enviar notificaciones por email')),
                ('notificaciones_push', models.BooleanField(default=True, help_text='Enviar notificaciones push')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('conductor_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rastreo_asignado', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_rastreo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Rastreo',
                'verbose_name_plural': 'Configuraciones de Rastreo',
                'unique_together': {('empresa', 'conductor_asignado')},
            },
        ),
        migrations.CreateModel(
            name='UbicacionCamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=8, help_text='Latitud de la ubicación', max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=8, help_text='Longitud de la ubicación', max_digits=11)),
                ('direccion', models.CharField(blank=True, help_text='Dirección aproximada de la ubicación', max_length=255)),
                ('velocidad', models.DecimalField(blank=True, decimal_places=2, help_text='Velocidad en km/h', max_digits=5, null=True)),
                ('bateria', models.IntegerField(blank=True, help_text='Porcentaje de batería del dispositivo', null=True)),
                ('senal_gps', models.CharField(default='Buena', help_text='Calidad de la señal GPS', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Momento exacto de la ubicación')),
                ('activo', models.BooleanField(default=True, help_text='Indica si esta ubicación está activa')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ubicación del Camión',
                'verbose_name_plural': 'Ubicaciones del Camión',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['conductor', '-timestamp'], name='clientes_ub_conduct_bba3f9_idx'), models.Index(fields=['activo', '-timestamp'], name='clientes_ub_activo_268b8a_idx')],
            },
        ),
    ]
